server:
  port:
    8080

spring:
  application:
    name:
      gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/users/**
        - id: user
          uri: lb://USER
          predicates:
              - Path=/api/user/**
        - id: student
          uri: lb://STUDENT
          predicates:
            - Path=/api/student/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
