### Check subject compatibility over course
POST http://localhost:8082/api/university/course/alsubjectdependency/check
Content-Type: application/json

{
  "firstSubject": "Chemistry",
  "secondSubject": "Physics",
  "thirdSubject": "Biology",
  "courseCode": "001"
}

### Check subject with results compatibility over course
POST http://localhost:8082/api/university/course/alsubjectdependency/checkwithresults
Content-Type: application/json

{
  "firstSubject": "Chemistry",
  "firstSubjectResult": "S",
  "secondSubject": "Physics",
  "secondSubjectResult": "B",
  "thirdSubject": "Biology",
  "thirdSubjectResult": "C",
  "courseCode": "001"
}

