### Login registered university
POST http://localhost:8082/api/university/login
Content-Type: application/json

{
  "email": "ucsc@gmail.com",
  "password": "ucsc@UNI123456"
}

### University registration - Entire registration form submittion
POST http://localhost:8082/api/university/register
Content-Type: application/json

{
  "name": "UOC",
  "address": "123",
  "islandRank": "1",
  "worldRank": "1000",
  "phone": "0362254890",

  "username": "ucsc",
  "email": "ucsc@gmail.com",
  "password": "TESTING@test123"
}