server:
  port:
    8083

spring:
  application:
    name:
      staff
  datasource:
    url: jdbc:mysql://localhost:3306/staff_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
#  datasource:
#    username: admin
#    password: adminugc
#    url: jdbc:mysql://ugcstudent-1.cibexrxavmfd.us-west-2.rds.amazonaws.com:3306/ugcStudents
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true