apiVersion: apps/v1
kind: Deployment
metadata:
  name: student
  labels:
    app: student
spec:
  replicas: 1
  template:
    metadata:
      name: student
      labels:
        app: student
    spec:
      containers:
        - name: student
          image: ucscgroupproject/student:1.0-SNAPSHOT
#          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
#      restartPolicy: Always
  selector:
    matchLabels:
      app: student
