### only for testing the blockchain construction
GET http://localhost:8/blockchain/test


### Adding a new block to the blockchain
POST http://localhost:8/blockchain/addblock
Content-Type: application/json

[
  {
    "transactionId": "1",
    "index": "1236547",
    "fullName": "khagsdl",
    "nic": "199931712165",
    "dateOfAdmission": "2011-10-03",
    "dateOfLeave": "2015-3-06"
  },
  {
    "transactionId": "2",
    "index": "9875462",
    "fullName": "jgyjkrfj",
    "nic": "200016548965315",
    "dateOfAdmission": "2012-10-08",
    "dateOfLeave": "2015-8-16"
  }
]


### Getting the entire blockchain
GET http://localhost:8/blockchain/getblockchain
