### Adding a new block to the blockchain
### Data will be forwarded by School service
### Public and Private keys are sent in String format but at the service level these will be decoded
### Public key String --> EC Coordinate Public key ::: Using X.509
### Private key String --> EC Coordinate Private key ::: Using PKCS8
### Resources To Follow:
### https://en.wikipedia.org/wiki/PKCS_8
### https://stackoverflow.com/questions/27682618/1convert-the-ecdsa-private-public-key-2verification-by-ecdsa
POST http://localhost:5/blockchain/addblock
Content-Type: application/json

{
  "transactions": [
    {
      "transactionId": "1",
      "index": "1236547",
      "fullName": "L.A.D.D.S. GUNAWARDHANA",
      "nic": "199931712165",
      "dateOfAdmission": "2011-10-03",
      "dateOfLeave": "2015-3-06"
    },
    {
      "transactionId": "2",
      "index": "9875462",
      "fullName": "D.C. PATHIRAGE",
      "nic": "200016548965315",
      "dateOfAdmission": "2012-10-08",
      "dateOfLeave": "2015-8-16"
    }
  ],
  "creatorName": "Hanwella Rajasinghe Central College",
  "creatorAddress": "School Ln, Hanwella",
  "creatorPublicKey": "MEYwEAYHKoZIzj0CAQYFK4EEAB8DMgAEsbJDZ0q6VFJ9xJ2RmXEo5ZFhJpDiB8Fe0Wc8Dhq/6zQH2KyuSzY92cOL7RW8dOLH",
  "creatorPrivateKey": "MHUCAQAwEAYHKoZIzj0CAQYFK4EEAB8EXjBcAgEBBBidgO4XIj3u7qkk8umXkwrJEK5f9gv2i5SgBwYFK4EEAB+hNAMyAASxskNnSrpUUn3EnZGZcSjlkWEmkOIHwV7RZzwOGr/rNAfYrK5LNj3Zw4vtFbx04sc="
}


### Getting the entire blockchain
GET http://localhost:5/blockchain/getblockchain


### Verifying a specific block in the blockchain
### Usually used by Staff, but can be used by anayone
### Public key and the associated block id will be sent
### String format public key transformed in to EC Cordinate format private key using X.509 encoded key spec (DECODING)
### Then signature will be verified usign public key and the associated hash of the block
### TODO: Check params. they are wrong in order
GET http://localhost:5/blockchain/verifyBlock?publicKey=2&publicKey=MEYwEAYHKoZIzj0CAQYFK4EEAB8DMgAEP1msaL2gbpRrZhTfBJuA+HGd8+a5HFbwtdX5a9k5p3Qb1qllNl1U2xT9WlHg0OHI


### Verifying the entire blockchain
GET http://localhost:5/blockchain/verifyBlockchain


### Generate a keypair - This will be used by School service
### Keypair consist of Public key and Private key
### Public key is a relatively short String
### Private key is a relatively long String
### Both are generated as Elliptic Curve Coordinate Formats and transformed to Strings using Base64 (ENCODING)
### This encoding the need to transfor the data, otherwise origina EC cordinates cant be directly forwarded or strore in MySQL DB
GET http://localhost:5/blockchain/generateKeypair
Content-Type: application/json

