### Student account verification email sending
POST http://localhost:3/api/email/sendVerifyAccountEmail
Content-Type: application/json

{
  "recipient": "dhanushkasandakelum711@gmail.com",
  "msgBody": "159753"
}