apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff
  labels:
    app: staff
spec:
  replicas: 1
  template:
    metadata:
      name: staff
      labels:
        app: staff
    spec:
      containers:
        - name: staff
          image: ucscgroupproject/staff:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: staff
