### Login registered student
POST http://localhost:8081/api/student/login
Content-Type: application/json

{
  "email": "dhanushkasandakelum711@gmail.com",
  "password": "dhanu@STU123456"
}


### Student registration - Section 1 Form check
POST http://localhost:8081/api/student/stuNicAndExamFormCheck
Content-Type: application/json

{
  "confirmNic": "199931712165",
  "indexNo": "sdfsdfsg",
  "nic": "199931712165",
  "nicDateOfIssue": "2022-06-30",
  "usedIDCopy": "C:\\fakepath\\AdobePIP.dll",
  "usedIDDateOfIssue": "2022-07-15",
  "usedIDNo": "dfgdfg",
  "usedIDType": "DL"
}

### Student registration - Section 2 Form check
POST http://localhost:8081/api/student/stuDetailsFormCheck
Content-Type: application/json

{
  "civilStatus": "1",
  "dob": "2022-07-20",
  "fullName": "gdg",
  "gender": "1",
  "nameWithInitials": "sdfsdf",
  "pob": "2",
  "title": "miss"
  "phone": "0775642956"
}

### Student registration - Section 3 Form check
POST http://localhost:8081/api/student/loginDetailsFormCheck
Content-Type: application/json

{
  "email": "dhanushkasandakelum711@gmail.com",
  "password": "dhanu@STU123456"
}

### Student registration - Entire registration form submittion
POST http://localhost:8081/api/student/studentRegister
Content-Type: application/json

{
  "confirmNic": "199931712165",
  "indexNo": "sdfsdfsg",
  "nic": "199931712165",
  "nicDateOfIssue": "2022-06-30",
  "usedIDCopy": "C:\\fakepath\\AdobePIP.dll",
  "usedIDDateOfIssue": "2022-07-15",
  "usedIDNo": "dfgdfg",
  "usedIDType": "DL",

  "civilStatus": "1",
  "dob": "2022-07-20",
  "fullName": "gdg",
  "gender": "1",
  "nameWithInitials": "sdfsdf",
  "pob": "2",
  "title": "miss",
  "phone": "+94775642956",

  "username": "Dhanushka",
  "email": "dhanushkasandakelum711@gmail.com",
  "password": "dhanu@STU123456"
}