### Get step 1 form
GET http://localhost:8081/api/student/universityAdmission/step1Form?username=Dhanushka

### Submit step 1 form
POST http://localhost:8081/api/student/universityAdmission/step1Form
Content-Type: application/json

{
  "permanentAddress": "131/c Kahatapitiya hanwella",
  "administrativeDistrict": "Colombo",
  "fixedTelephone": "0775642956",
  "residenceStartLivingDate": "2020-10-12",
  "race": "Sinhala",
  "religion": "Buddhism",
  "citizenByDescent": "Yes",
  "contactAddress": "131/c Kahatapitiya hanwella",
  "postalCode": "10650",

  "fatherFullname": "Dhanushka sandakelum",
  "motherFullname": "asfsdg sandakelum",
  "guardianFullname": "Dhanushka sandakelum",

  "contactPersonType": "Father",
  "contactPersonAddress": "131/c Kahatapitiya hanwella",
  "contactPersonFixedTelephone": "0775642956",
  "contactPersonMobile": "0775642956",

  "username": "Dhanushka"
}

### Get step 2 form
GET http://localhost:8081/api/student/universityAdmission/step2Form?username=Dhanushka

### Submit step 2 form
POST http://localhost:8081/api/student/universityAdmission/step2Form
Content-Type: application/json

{
  "olCategory": "localOL",
  "olYear": "2016",
  "olIndex": "19000553",
  "olNameUsed": "Dhanushka sandakelum",
  "olResultsAcceptance": "true",

  "alAdministrativeDistrictTaken": "Colombo",
  "alAdministrativeDistrictConsidered": "Colombo",
  "alResultsAcceptance": "true",

  "username": "Dhanushka"
}


### Submit step 3 form
POST http://localhost:8081/api/student/universityAdmission/step3Form
Content-Type: application/json

{
  "candidateType": "School",

  "schoolName": "HRCC",
  "schoolAddress": "131/ C Kahatapitiya",
  "schoolAdministrativeDistrict": "Colombo",
  "schoolTelephone": "0775642956",
  "schoolDateOfAdmission": "1999-11-12",

  "additionalSchools": [
    {
      "additionalSchoolName": "ABC",
      "additionalSchoolDistrict": "Colombo",
      "additionalSchoolFrom": "2000-05-12",
      "additionalSchoolTo": "2005-05-03"
    },
    {
      "additionalSchoolName": "DEF",
      "additionalSchoolDistrict": "Polonnaruwa",
      "additionalSchoolFrom": "2000-05-12",
      "additionalSchoolTo": "2005-05-03"
    }
  ],

  "alreadyRegisteredAsInternalStudent": "false",
  "alreadyReceivedForeignScholarships": "true",

  "username": "Dhanushka"
}

### Get step 4 form
GET http://localhost:8081/api/student/universityAdmission/step4Form?username=Dhanushka

### Submit step 4 form
POST http://localhost:8081/api/student/universityAdmission/step4Form
Content-Type: application/json

{
  "unicodeRecords": [
    {
      "unicode": "001A",
      "courseName": "Medicine",
      "universityName": "University of Colombo"
    }
  ],
  "username": "Dhanushka"
}
