server:
  port:
    2

spring:
  application:
    name:
      notification

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# OTP Sending
twilio:
  account_sid: ACcdb49e06af08237f6ab779f845249856
  auth_token: 92fb9a0a28eb1c39555dd65c56c881b7
  trail_number: +12398429286

