kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
      - name: frontend-web
        image: ucscgroupproject/frontend-web
        ports:
        - containerPort: 80