# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: frontend-web
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend-web
#   template:
#     metadata:
#       labels:
#         app: frontend-web
#     spec:
#       containers:
#       - name: frontend-web
#         image: ucscgroupproject/frontend-web
#         ports:
#         - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
spec:
  selector:
    matchLabels:
      app: frontend-web
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: frontend-web
          image: ucscgroupproject/frontend-web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80