# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-web
#   labels:
#     app: frontend-web
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 80
#     protocol: TCP
#     nodePort: 31000
#   selector:
#     app: frontend-web

apiVersion: v1
kind: Service
metadata:
  name: frontend-web-service
spec:
  selector:
    app: frontend-web
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP