apiVersion: apps/v1
kind: Deployment
metadata:
  name: university
  labels:
    app: university
spec:
  replicas: 1
  template:
    metadata:
      name: university
      labels:
        app: university
    spec:
      containers:
        - name: university
          image: ucscgroupproject/university:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: university
