### Create school
POST http://localhost:8084/api/school/default
Content-Type: application/json

{
  "schoolName": "Hanwella rajasinghe College",
  "districtName": "Colombo"
}

### Get School by id
GET http://localhost:8084/api/school/default?schoolId=5

### Get all Schools
GET http://localhost:8084/api/school/default/all

### Update school
PUT http://localhost:8084/api/school/default?schoolId=5
Content-Type: application/json

{
  "schoolName": "Hanwella rajasinghe central College",
  "districtName": "Colombo"
}

### Delete School
DELETE http://localhost:8084/api/school/default?schoolId=5