### Get Document
GET http://localhost:8084/api/school/document?username=RC

### Create document
POST http://localhost:8084/api/school/document
Content-Type: application/json

{
  "schoolUsername": "RC",
  "studentRecords": [
    {
      "stuIndex": "1236547",
      "fullName": "L.A.D.D.S. GUNAWARDHANA",
      "nic": "199931712165",
      "admissionDate": "2011-10-03",
      "leaveDate": "2015-3-06",
      "validity": true
    },
    {
      "stuIndex": "9875462",
      "fullName": "D.C. PATHIRAGE",
      "nic": "200016548965315",
      "admissionDate": "2012-10-08",
      "leaveDate": "2015-8-16",
      "validity": false
    }
  ],
  "status": false
}

### Update document
PUT http://localhost:8084/api/school/document
Content-Type: application/json

{
  "schoolUsername": "RC",
  "studentRecords": [
    {
      "id": 1,
      "stuIndex": "1236547",
      "fullName": "L.A.D.D.S. GUNAWARDHANA",
      "nic": "199931712165",
      "admissionDate": "2011-10-03",
      "leaveDate": "2015-3-06",
      "validity": false
    },
    {
      "id": 2,
      "stuIndex": "9875462",
      "fullName": "D.C. PATHIRAGE",
      "nic": "200016548965315",
      "admissionDate": "2012-10-08",
      "leaveDate": "2015-8-16",
      "validity": true
    }
  ]
}


