apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-manager
  labels:
    app: file-manager
spec:
  replicas: 1
  template:
    metadata:
      name: file-manager
      labels:
        app: file-manager
    spec:
      containers:
        - name: file-manager
          image: ucscgroupproject/file-manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 1002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: file-manager
