server:
  port:
    8080

spring:
  application:
    name:
      gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user
          uri: lb://USER
          predicates:
              - Path=/api/user/**
        - id: student
          uri: lb://STUDENT
          predicates:
            - Path=/api/student/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
