server:
  port:
    8080

spring:
  application:
    name:
      gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: student
          uri: lb://STUDENT
          predicates:
            - Path=/api/student/**
        - id: university
          uri: lb://UNIVERSITY
          predicates:
            - Path=/api/university/**
        - id: staff
          uri: lb://STAFF
          predicates:
            - Path=/api/staff/**
        - id: school
          uri: lb://SCHOOL
          predicates:
            - Path=/api/school/**
        - id: email
          uri: lb://EMAIL
          predicates:
            - Path=/api/email/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/notification/**
        - id: selection-process
          uri: lb://SELECTION-PROCESS
          predicates:
            - Path=/api/selection-process/**
        - id: zscore
          uri: lb://ZSCORE
          predicates:
            - Path=/api/zscore/**
        - id: blockchain
          uri: lb://BLOCKCHAIN
          predicates:
            - Path=/api/blockchain/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
