server:
  port:
    8081

spring:
  application:
    name:
      user
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

gateway:
  ip: host.docker.internal

token:
  expiration_time: 86400000 # 10 Days
  secret: adasdklngsgl53d1g3d1g3d1g3d51fg3df1g35d1g31