server:
  port:
    5

spring:
  application:
    name:
      crypto-signer
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: crypto_db
      port: 27017
      host: localhost


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true