server:
  port:
    5000

spring:
  application:
    name:
      blockchain
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootuser
      database: blockchain_db
      port: 27017
      host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true