server:
  port:
    5

spring:
  application:
    name:
      blockchain
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: blockchain_db
      port: 27017
      host: localhost
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true