server:
  port:
    8

spring:
  application:
    name:
      blockchain
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: blockchain_db
      port: 27017
      host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true